baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Steve Ivkov's Site"
subtitle="My awesome DS site"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
